### ISSUE TITLE
Damagelog Events not shown?

### ISSUE THREAD

**Issue by Alabama4** [Tommy228/TTTDamagelogs#343]
Hey, i recently ran into a Problem where some events are not shown for example if you kill yourself its not shown/ damage yourself, if you die by a prop its not shown anymore, if you die by a headcrablauncher its not shown and a few more, i believe its since the update 3.00, could anyone help me out with fixing that? :)

Regards

**Comment by MinIsMin** [comment]
Confirmed. I will look into all I can find.

Currently known (and fixed?):

- [x] prop (fixed with https://github.com/Tommy228/TTTDamagelogs/commit/4a603dbb08a0a9212db3e2d3e9144f7282128ce7#diff-7635be68d866796324995b795a00fe8a)
- [ ] headcrablauncher
- [ ] fire (using a flaregun on an entity that burns you)

**Comment by Alabama4** [comment]
Hey, thanks for the fast reply, but i've tried the prop fix, it still does not seem to work, i've download the newest version, where you already invented the lines & it didnt seem to show any kills in the manager, (i've tried it with Bots & on singleplayer), and is there any reason to remove Water damage?, because if you drown its not shown either

Regards

**Comment by MinIsMin** [comment]
There are many changes between 3.0 and the current master version which may not work.
The fix for propkills checked for `prop_physics` but now also checks for `func_physbox` and should be fully working now.
Drownings are seperated to it's own event: [events/drownings.lua](https://github.com/Tommy228/TTTDamagelogs/blob/master/lua/damagelogs/shared/events/drownings.lua)

**Comment by Alabama4** [comment]
Ok i see, thanks :), would it be possible if you could add a event which is caused when a player pushes another player with a crowbar 4 example?, i tried doing it myself but didnt really get behind it :D

**Comment by MinIsMin** [comment]
I will look into readding it, some code is already there:
https://github.com/Tommy228/TTTDamagelogs/blob/5c0408d66668f1b9e8dd1b7b1bd4dff6095211cb/lua/damagelogs/client/listview.lua#L280-L283

**Comment by Alabama4** [comment]
Is it better to upload the old Damagelog for now? (if yes where could i get it) or just wait until it gets fixed?

**Comment by MinIsMin** [comment]
You can get the old (2.4.0) version from here: https://github.com/Tommy228/TTTDamagelogs/archive/fafffdd6903c05b8c27d4de0764783e82abd68fc.zip
You need to know for yourself if you want to use the old or new version.
We will try to fix all bugs and issues and then release a new, stable version (no ETA yet).

**Comment by Alabama4** [comment]
Ok thanks, also another question:

Is it possible to add a Damagelog line without creating its own event for it? for example with handcuffs:

Player a handcuffed player b (add a line into Primaryattack like:
Damagelog:AddLine(Player a put Player B into Handcuffs) ?

Regards

**Comment by iagrib** [comment]
I don't think so, because every log entry is tied to an event (and uses event:ToString() method to actually get the line in text to display). Creating an event shouldn't be very hard though.

**Comment by MinIsMin** [comment]
iagrib is right, you need a damagelog event since it manages e.g. the hooks, colors, text formatting and user stuff like `Highlight` and `RightClick`.

Please be aware to the actual topic of this issue, so other contributers can keep better track of the missing events.

**Comment by Alabama4** [comment]
Oh ok sorry my bad :P, was just a question ^_^

**Comment by Alabama4** [comment]
Hey i also just noticed that if you die by lava on minecraft_ttt_b5 youre not in the logs that you died(not sure if already fixed)

**Comment by MinIsMin** [comment]
Using the newest master version, dying in lava is recorded by [events/suicide.lua](https://github.com/Tommy228/TTTDamagelogs/blob/master/lua/damagelogs/shared/events/suicide.lua).
